# Generated by Django 6.0.3 on 2026-03-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
